Refactor calendars, introduce calendar customization
dr-prodigy/python-holidays pull request #1122
Opened 2023-04-26 04:05 UTC by arkid15r

## Proposed change
Prettify the code structure around recently updated calendars:
  - Split calendars into multiple files.
  - Add calendar customization mechanism (Islamic).
  - Update tests: fix estimated holidays names.
  - Update Pakistan Ashura dates.

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [x] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency upgrade (version update)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] This PR is filed against `beta` branch of the repository
- [x] This PR doesn't contain any merge conflicts and has clean commit history
- [x] The code style looks good: `make pre-commit`
- [x] All tests pass locally: `make test`, `make tox` (we strongly encourage adding tests to your code)
- [x] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

[contributing-guidelines]: https://github.com/dr-prodigy/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/dr-prodigy/python-holidays/tree/beta/docs/source

2023-04-26 04:07 UTC, arkid15r commented on holidays/countries/pakistan.py
@KJhellico, could you look closer on the Pakistan holidays changes (Ashura). I'm not sure if I've done everything right.

2023-04-26 10:42 UTC, KJhellico commented
`exact_dates` realization: 🚀

2023-04-26 11:29 UTC, KJhellico requested changes
It seems that in 2022, Ashura in Pakistan was on [August 8-9](https://www.geo.tv/latest/431501-muharram-2022-govt-announces-two-day-holiday-for-ashura).

2023-04-26 11:29 UTC, KJhellico commented on holidays/countries/pakistan.py
> +        2022: ((AUG, 8),),
```suggestion
        2022: ((AUG, 9),),
```

2023-04-26 11:29 UTC, KJhellico commented on tests/countries/test_pakistan.py
> +            ("2022-08-08", "Ashura"),
```suggestion
            ("2022-08-08", "Ashura"),
            ("2022-08-09", "Ashura"),
```

2023-04-26 12:20 UTC, KJhellico commented
And `BEGIN_RAMADAN_DATES` is missing.

2023-04-27 16:20 UTC, arkid15r commented on holidays/countries/united_arab_emirates.py
> +        self._add_eid_al_fitr_day_three(f"{eid_al_adha} Holiday")
Renamed

2023-04-27 16:21 UTC, arkid15r commented
> And `BEGIN_RAMADAN_DATES` is missing.

It was defined but unused so I cleaned that up.
It's been restored (I changed the name a bit though).

2023-04-28 10:53 UTC, KJhellico commented on holidays/holiday_groups.py
> +        estimated_label = getattr(self, "estimated", "estimated")
In Pakistan (only use for now), this attribute is named `estimated_label`, need to synchronize :)

2023-05-01 17:12 UTC, KJhellico reviewed
LGTM.

2023-05-01 17:13 UTC, KJhellico approved these changes
Let's go!

2023-05-01 17:15 UTC, merged