Added missing bridge days for Russia for 2023
dr-prodigy/python-holidays pull request #1142
Opened 2023-05-04 21:21 UTC by leeloo-1337

## Proposed change

Added missing bridge days for Russia for 2023. Determined yearly by the government: https://www.consultant.ru/document/cons_doc_LAW_425407/

## Type of change

- [ ] New country/market holidays support (thank you!)
- [x] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency upgrade (version update)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] This PR is filed against `beta` branch of the repository
- [x] This PR doesn't contain any merge conflicts and has clean commit history
- [x] The code style looks good: `make pre-commit`
- [x] All tests pass locally: `make test`, `make tox` (we strongly encourage adding tests to your code)
- [ ] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

[contributing-guidelines]: https://github.com/dr-prodigy/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/dr-prodigy/python-holidays/tree/beta/docs/source

2023-05-05 00:19 UTC, arkid15r requested changes
Thank you for your contribution!

Please fix the issues and request the review again.

2023-05-05 00:19 UTC, arkid15r commented on holidays/countries/russia.py
> +        2023: ((MAY, 8, "День Победы"),), # Bridge day for 8/Jan, src: https://www.consultant.ru/document/cons_doc_LAW_425407/
These keys are identical and the latter key overwrites former one.
This is why we emphasize on importance of [adding tests](https://github.com/dr-prodigy/python-holidays/blob/beta/tests/countries/test_russia.py).

2023-05-05 00:19 UTC, arkid15r commented on holidays/countries/russia.py
> +        2023: ((FEB, 24, "День защитника Отечества"),), # Bridge day for 1/Jan, src: https://www.consultant.ru/document/cons_doc_LAW_425407/
Could you really run the pre-commit and make sure the code style looks good? Thank you!

2023-05-05 02:22 UTC, arkid15r commented
Some issues still need to be fixed. Could you also add tests for these holidays?

2023-05-05 02:29 UTC, leeloo-1337 commented
> Some issues still need to be fixed. Could you also add tests for these holidays?

The test ran okay on the latest one. Unless I'm doing it wrong?

2023-05-05 15:48 UTC, arkid15r commented on holidays/countries/russia.py
> +            # Bridge days for 01/Jan & 08/Jan
Could you keep the link to the law too?

2023-05-05 15:48 UTC, arkid15r commented on tests/countries/test_russia.py
> +    def test_2023(self):
Thanks for adding the tests.

Could you keep the 2018's tests together?

2023-05-05 19:32 UTC, leeloo-1337 commented on holidays/countries/russia.py
> +            # Bridge days for 01/Jan & 08/Jan
> Could you keep the link to the law too?

Done

2023-05-09 16:43 UTC, arkid15r reviewed
Thank you for addressing the comments, marking this as ready for beta.

2023-05-09 17:18 UTC, merged