Fix observance logic for laborable holidays.
dr-prodigy/python-holidays pull request #758
Opened 2022-10-22 01:09 UTC by kasya

Update tests.
Resolves #745

2022-10-22 02:15 UTC, arkid15r commented on holidays/countries/uruguay.py
> +                self[dt - rd(weekday=MO(-1))] = name
```suggestion
                self[dt + rd(weekday=MO(-1))] = name
```

2022-10-22 02:15 UTC, arkid15r commented on test/countries/test_uruguay.py
> +            date(2021, 2, 15),
Sort here and below.

2022-10-22 10:06 UTC, KJhellico requested changes

2022-10-22 10:06 UTC, KJhellico commented on holidays/countries/uruguay.py
> +            easter(year) - rd(weekday=TH(-1))
```suggestion
            easter(year) + rd(weekday=TH(-1))
```

2022-10-22 10:06 UTC, KJhellico commented on holidays/countries/uruguay.py
> +            easter(year) - rd(weekday=FR(-1))
```suggestion
            easter(year) + rd(weekday=FR(-1))
```

2022-10-22 10:06 UTC, KJhellico commented on holidays/countries/uruguay.py
> +                self[dt - rd(weekday=MO(-1))] = name
```suggestion
                self[dt + rd(weekday=MO(-1))] = name
```

2022-11-06 20:57 UTC, merged

2022-11-06 20:57 UTC, dr-prodigy commented
Thank you very much @kasya ! 👍