Adding financial holidays - Hurricane Gloria and Sandy
dr-prodigy/python-holidays pull request #833
Opened 2022-12-10 01:06 UTC by SnowX65

Hurricane sandy - October 29 & 30, 2012

Hurricane Gloria - September 27th, 1985

https://www.sandiegouniontribune.com/sdut-hurricane-sandy-shuts-stock-trading-for-2-days-2012oct29-story.html

2022-12-10 09:25 UTC, KJhellico requested changes

2022-12-10 09:25 UTC, KJhellico commented on holidays/financial/ny_stock_exchange.py
> +            ] = "Weather related clousre due to the impact of Hurricane Gloria"
```suggestion
            ] = "Hurricane Gloria"
```

2022-12-10 09:25 UTC, KJhellico commented on holidays/financial/ny_stock_exchange.py
> +            ] = "Weather related clousre due to the impact of Hurricane Sandy"
```suggestion
            ] = "Hurricane Sandy"
```

2022-12-10 09:25 UTC, KJhellico commented on holidays/financial/ny_stock_exchange.py
> +            ] = "Weather related clousre due to the impact of Hurricane Sandy"
```suggestion
            ] = "Hurricane Sandy"
```

2022-12-10 09:25 UTC, KJhellico commented on test/financial/test_ny_stock_exchange.py
> +            ),  # Weather related clousre due to the impact of Hurricane Gloria
```suggestion
            ),  # Hurricane Gloria
```

2022-12-10 09:25 UTC, KJhellico commented on test/financial/test_ny_stock_exchange.py
> +            ),  # Weather related clousre due to the impact of Hurricane Sandy
```suggestion
            ),  # Hurricane Sandy
```

2022-12-10 09:25 UTC, KJhellico commented on test/financial/test_ny_stock_exchange.py
> +            ),  # Weather related clousre due to the impact of Hurricane Sandy
```suggestion
            ),  # Hurricane Sandy
```

2022-12-11 11:16 UTC, KJhellico approved these changes

2022-12-12 15:45 UTC, arkid15r reviewed
Suggested the tests fix.
Otherwise looks good!

2022-12-12 15:45 UTC, arkid15r commented on test/financial/test_ny_stock_exchange.py
> +            date(2012, OCT, 29),  # Hurricane Sandy
```suggestion
            date(2012, OCT, 30),  # Hurricane Sandy
```

2022-12-12 16:15 UTC, SnowX65 commented on test/financial/test_ny_stock_exchange.py
> +            date(2012, OCT, 29),  # Hurricane Sandy
Thanks missed that one!

2022-12-13 23:28 UTC, merged