Optimize observed holidays (part 2)
dr-prodigy/python-holidays pull request #952
Opened 2023-02-16 13:12 UTC by KJhellico

Angola, Eswatini, Kazakhstan, Kenya, Malawi, Singapore, South Africa

2023-02-16 14:10 UTC, PPsyrius requested changes
Seems good IMO, this one can be improved though, now that we're touching them anyway.

2023-02-16 14:10 UTC, PPsyrius commented on holidays/countries/kenya.py
> +        2020: ((FEB, 11, "President Moi Celebration of Life Day	"),),
Remove extra space here:
```suggestion
        2020: ((FEB, 11, "President Moi Celebration of Life Day"),),
```

2023-02-16 14:10 UTC, PPsyrius commented on holidays/countries/south_africa.py
> +            self[date(2000, JAN, 3)] = "Y2K changeover (Observed)"
Here's the one for the special holidays section:
```python
        2000: (
            (JAN, 2, "Y2K changeover"),
            (JAN, 3, "Y2K changeover (Observed)"),
        ),
```

2023-02-16 14:10 UTC, PPsyrius commented on holidays/countries/singapore.py
>              self[date(2007, JAN, 2)] = "Hari Raya Haji (Observed)"
This one could also be declared in the special holidays section instead
```suggestion
        # special case (observed from previuos year)
        if self.observed and year == 2007:
            self[date(2007, JAN, 2)] = "Hari Raya Haji (Observed)"
```

2023-02-16 14:10 UTC, PPsyrius commented on holidays/countries/singapore.py
>              self[date(2007, JAN, 2)] = "Hari Raya Haji (Observed)"
```python
        2007: ((JAN, 2, "Hari Raya Haji (Observed)"),),
```

2023-02-16 17:43 UTC, arkid15r reviewed
This is a huge great-quality work! Thank you for optimizing the performance issues!

LGTM

2023-02-17 16:41 UTC, merged

2023-02-17 16:42 UTC, arkid15r commented
Great stuff 👍👍